spring:
  datasource:
    url: jdbc:mysql://localhost:3306/videogames?verifyServerCertificate=false&useSSL=false&requireSSL=false
    username: api-service-account
    password: superSecurePassword
  jpa:
    hibernate:
      ddl-auto: validate
